import type { Metadata } from "next";

/* Fontes */


/* Estilos */
import "./globals.css";

import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import Navbar from './Navbar/page'
import Footer from "./Footer/page";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
          <Navbar/>
          {children}
          <Footer/>
      </body>
    </html>
  );
}
